# Generated by Django 2.0 on 2018-05-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0046_choice_next_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='next_page',
            field=models.ForeignKey(help_text='This is the default next page for this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_formquestion_set', to='wizard_builder.Page', verbose_name='Default next page'),
        ),
        migrations.AddField(
            model_name='page',
            name='last_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_page',
            field=models.ForeignKey(blank=True, help_text='This overrides the default next page set above.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard_builder.Page'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard_builder.Page'),
        ),
    ]
